name: http-server

releases:
- name: http-server
  version: latest

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest

instance_groups:
- name: http-server
  instances: 1
  azs: [az1]
  vm_type: small
  stemcell: default
  networks:
  - name: services
  jobs:
  - name: http-server
    release: http-server
    properties:
      port: 8081

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
